sudo: required
language: android
dist: trusty
jdk: oraclejdk8  
python: 
  - "3.6"
android:
  components:
    - platform-tools
    - tools
    - build-tools-30.0.2
    - android-30
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
before_install:
  - yes | sdkmanager "platforms;android-30"
  - sudo apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev
  - wget https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tgz
  - tar -xf Python-3.8.0.tgz
  - cd Python-3.8.0
  - ./configure --enable-optimizatio
  - make -j 8
  - sudo make altinstall
  - python3.8 --version
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
before_script:
  - touch local.properties
script:
   - ./gradlew build connectedCheck
   - ./gradlew assembleDebug

notifications:
  email:
    - ivan.montiel.c@gmail.com
