language: android
dist: trusty
jdk: oraclejdk8  
#python: 
#  - "3.6"
android:
  components:
    - platform-tools
    - tools
    - build-tools-30.0.2
    - android-30
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
addons:
  apt:
    packages:
    - python3
before_install:
  - yes | sdkmanager "platforms;android-30"
before_script:
  - touch local.properties
script:
   - ./gradlew assembleDebug

notifications:
  email:
    - ivan.montiel.c@gmail.com
