version: 2.1

orbs:
  android: circleci/android@0.2.1
  python: circleci/python@1.0.0

jobs:
  build:
  
    executor: android/android

    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install software-properties-common
      #- run: sudo chown -R circleci:circleci /usr/local/bin
      #- run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run: touch local.properties
      - run: ./gradlew androidDependencies
      - run:
          command: ./gradlew build
