version: 2.1

orbs:
  android: circleci/android@0.2.1
  python: circleci/python@1.0.0

jobs:
  build:

    required:
      machine:
        image: ubuntu-2004:202010-01 # recommended linux image

    executor: android/android

    steps:
      - checkout
      - python/dist
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run python manage.py test
      - run: touch local.properties
      - run: ./gradlew androidDependencies
      - run:
          command: ./gradlew build
