version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
  
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
      
    executor: android/android

    steps:
      - checkout
      - run: sudo apt-get install python3-distutils
      - run: touch local.properties
      - run: ./gradlew androidDependencies
      - run:
          command: ./gradlew build
